// <auto-generated />
using LR_web2.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR_web2.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241207100554_название_миграции")]
    partial class название_миграции
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LR_web2.Server.Models.ProductImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.Property<int?>("productId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("images");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Property", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("property_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("properties");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Travel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("travels");
                });

            modelBuilder.Entity("LR_web2.Server.Models.ProductImage", b =>
                {
                    b.HasOne("LR_web2.Server.Models.Travel", "product")
                        .WithMany("Images")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Property", b =>
                {
                    b.HasOne("LR_web2.Server.Models.Travel", "product")
                        .WithMany("Properties")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Travel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
