// <auto-generated />
using LR_web2.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LR_web2.Server.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LR_web2.Server.Models.Image", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.Property<long?>("productId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Property", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("productId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("property_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Travel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("travels");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Image", b =>
                {
                    b.HasOne("LR_web2.Server.Models.Travel", "product")
                        .WithMany("Images")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Property", b =>
                {
                    b.HasOne("LR_web2.Server.Models.Travel", "product")
                        .WithMany("Properties")
                        .HasForeignKey("productId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("LR_web2.Server.Models.Travel", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
